### ISSUE TITLE
Full of bugs! Unplayable.

### ISSUE THREAD

**Issue by amber-rose** [Hugobros3/chunkstories-core#2]
Sound ok at start. Lot's of bugs and author refuses to do any testing. He only have 1 bug test file here: https://github.com/Hugobros3/chunkstories-core/blob/master/src/test/java/BigVoxelLogicTest.kt 
obvious that author Hugobros3 care very much about his game and like to teset it. He complains that no one will play his game because it has buggy features. Sorry I give you star on github out of pity!!

**Comment by amber-rose** [comment]
https://github.com/Hugobros3/chunkstories-core/pull/3

**Comment by Hugobros3** [comment]
See https://github.com/Hugobros3/chunkstories/issues/7
